source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.oschina.net/geniusbrother/podSpec.git'
platform :ios, '7.0'

target 'HZExtend-Demo' do


pod 'HZExtend', :path => '../'
pod 'Masonry', '~> 1.0.0'

end
